import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-4xl mx-auto p-4">
        <nav className="flex justify-between items-center mb-4">
          <a href="/" className="text-xl font-bold">MyBlog</a>
          <div>
            <a href="/login" className="mr-4">Login</a>
            <a href="/register">Register</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
